### ISSUE TITLE
Cannot disable autoRegister on init

### ISSUE THREAD

**Issue by stasix** [one-signal/OneSignal-iOS-SDK#1]
Hi!

I cannot disable autoRegister. Passing false to autoRegister in initWithLaunchOptions does not help and still triggers automatic registration. I need to delay the registration.
I'm using 1.9.0 version.

I'd appreciate any help.

**Comment by jkasten2** [comment]
Hello,

I just tested version 1.9.0 with autoRegister: false and it working correctly. Which version of iOS are you seeing this issue on?

How are you resetting the push notification prompt? If your turning off the device when you see the prompt you will need to fully uninstall the app and reinstall it before opening it again. Otherwise iOS will reprompt the user right way when the app opens.

See our documentation on [Resetting the iOS Notification Permission Prompt](http://documentation.onesignal.com/v2.0/docs/common-problems#resetting-the-ios-notification-permission-prompt).

Thanks.

**Comment by stasix** [comment]
Hi, thanks for the quick prompt.
I'm seeing this on iOS9.

On Thursday, June 18, 2015, Josh Kasten <notifications@github.com> wrote:

> Hello,
>
> I just tested version 1.9.0 with autoRegister: false and it working
> correctly. Which version of iOS are you seeing this issue on?
>
> How are you resetting the push notification prompt? If your turning off
> the device when you see the prompt you will need to fully uninstall the app
> and reinstall it before opening it again. Otherwise iOS will reprompt the
> user right way when the app opens.
>
> See our documentation on Resetting the iOS Notification Permission Prompt
> <http://documentation.onesignal.com/v2.0/docs/common-problems#resetting-the-ios-notification-permission-prompt>
> .
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/one-signal/OneSignal-iOS-SDK/issues/1#issuecomment-112961795>
> .
>


-- 
--
Stas Goferman
CEO, Bazaart <http://www.bazaart.me/>

**Comment by jkasten2** [comment]
Hello, sorry about the delay. I identified an issue where our SDK prompts for push notifications on the 2nd cold start of the app. I'll attach a commit to this issue when I have a fix.

Thanks.

**Comment by stasix** [comment]
Great! Thanks!

--
Stas Goferman
CEO, Bazaart <http://www.bazaart.me/>

**Comment by stasix** [comment]
@jkasten2, can you update the pod as well to 1.9.2?

**Comment by jkasten2** [comment]
Just pushed our update to cocoa pods. Let us know if this version fixes the issue for you and we can close this issue.

Thanks.

**Comment by stasix** [comment]
didRegisterForRemoteNotificationsWithDeviceToken is being called when I init OneSignal on the app launch. Maybe it's an iOS9 issue.
Instead, I'm deferring OneSignal init with autoRegister set to True at a later stage in the app. Seems to work.

**Comment by jkasten2** [comment]
Are you seeing iOS prompt for notification permissions when OneSignal initWithLaunchOptions is called with autoRegister: false? Or just seeing the firing of `application:didRegisterForRemoteNotificationsWithDeviceToken:`?

I have test 1.9.2 of our OneSignal SDK with iOS 8.2 and iOS 9 beta 2 and autoRegister: false does not prompt the user for the notification permission.

The `UIApplicationDelegate` `application:didRegisterForRemoteNotificationsWithDeviceToken:` selector is always fired from the `initWithLaunchOptions:` selectors on OneSignal as it always calls `[[UIApplication sharedApplication] registerForRemoteNotifications]` on iOS 8+ devices. This is ok as it does not prompt the user for notification permissions. The call to `registerUserNotificationSettings:` inside of OneSignal's `registerForPushNotifications` selector does the prompting. The `autoRegister` could be better named as autoPrompt but this was named this way before iOS 8 was released.

Thanks.

**Comment by stasix** [comment]
I'm seeing the firing of application:didRegisterForRemoteNotificationsWithDeviceToken without prompt. So I understand this is a desired behaviour.
I defer OneSignal init, only the first time, until the user is prompted at a specific point in the app. In the successive app launches, OneSignal inits on launch. It this OK?

**Comment by jkasten2** [comment]
Currently the firing of `application:didRegisterForRemoteNotificationsWithDeviceToken` when your app starts is by design. It shouldn't create an issue, do you have another SDK/plugin this is creating a problem with?

We would prefer to understand and fix the issue however if you need to go this route with your app you will need to wrap any other method calls to OneSignal with your same logic. We did not intend for OneSignal not be called when your app starts. You also won't be able to see your user opt in rate on our dashboard and anything the user does before accepting will not be included in their totals.

Thanks.

**Comment by stasix** [comment]
Josh, we have some logic in application:didRegisterForRemoteNotificationsWithDeviceToken with another functionality.
How is application:didRegisterForRemoteNotificationsWithDeviceToken fired without user prompt in the first run? Is the deviceToken in such case is nil?

**Comment by jkasten2** [comment]
In iOS 8 Apple split up push notifications into 2 parts.
* Remote notifications - You can get a validate device token without permission from the user and it can be used for content-available notifications. It can not however display a notification, play a sound, or set a badge icon without prompting the user however. This id is requested with [registerForRemoteNotifications](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIApplication_Class/index.html#//apple_ref/occ/instm/UIApplication/registerForRemoteNotifications) and fires [application:didRegisterForRemoteNotificationsWithDeviceToken:](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIApplicationDelegate_Protocol/index.html#//apple_ref/occ/intfm/UIApplicationDelegate/application:didRegisterForRemoteNotificationsWithDeviceToken:).
* Displaying Notifications - To display notifications and set badges (locally or remotely) requires the user to accept a notification permissions prompt. This is requested by calling [registerUserNotificationSettings:](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIApplication_Class/index.html#//apple_ref/occ/instm/UIApplication/registerUserNotificationSettings:).

See the documentation on [registerForRemoteNotifications](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIApplication_Class/index.html#//apple_ref/occ/instm/UIApplication/registerForRemoteNotifications) for the source of what I explained above.

If you only want to get the deviceToken/pushPush token if the user accepted permissions to display notifications you can use [IdsAvailable](http://documentation.onesignal.com/docs/ios-sdk-api#IdsAvailable). pushToken will be nil if the user has not accepted the prompt yet or disabled notifications in the system settings for your app.

Thanks.

**Comment by stasix** [comment]
@jkasten2 - Thanks for clarifying this and for your time. This makes a lot sense now.
btw, we love OneSignal!
