### ISSUE TITLE
sendTags only sends one tag?

### ISSUE THREAD

**Issue by avishayil** [one-signal/OneSignal-iOS-SDK#12]
I'm calling `[oneSignal sendTags:properties]` while `properties` equals:
`properties	__NSCFDictionary *	20 key/value pairs	0x17fb7ce0`
and contains 20 key value strings.

After this runs it returns `success` but I can only see one tag on the OneSignal user page.

**Comment by jkasten2** [comment]
@avishayil I was not able to reproduce the issue with a dictionary with 20 key value pairs. Could you `NSLog` the contains of `properties`?

**Comment by jkasten2** [comment]
@avishayil Do have any nested arrays or non-string types in your `NSDictionary`?

**Comment by jkasten2** [comment]
@avishayil Closing this issue. Feel free to open the issue if you are able to reproduce it.
