### ISSUE TITLE
impossible to run application on simulator 

### ISSUE THREAD

**Issue by tlilioussam** [one-signal/OneSignal-iOS-SDK#14]
When i try to run application on simulator i have this error
-------------------------------------------------------------------------------------------------------------------------------------------
duplicate symbol _llvm.cmdline in:
    /Users/oussamtlili/Desktop/Wishibam-iOS/Pods/OneSignal/iOS_SDK/Framework/OneSignal.framework/OneSignal(GameThrive.o)
    /Users/oussamtlili/Desktop/Wishibam-iOS/Pods/OneSignal/iOS_SDK/Framework/OneSignal.framework/OneSignal(OneSignalTrackIAP.o)
duplicate symbol _llvm.embedded.module in:
    /Users/oussamtlili/Desktop/Wishibam-iOS/Pods/OneSignal/iOS_SDK/Framework/OneSignal.framework/OneSignal(GameThrive.o)
    /Users/oussamtlili/Desktop/Wishibam-iOS/Pods/OneSignal/iOS_SDK/Framework/OneSignal.framework/OneSignal(OneSignalTrackIAP.o)
duplicate symbol _llvm.cmdline in:
    /Users/oussamtlili/Desktop/Wishibam-iOS/Pods/OneSignal/iOS_SDK/Framework/OneSignal.framework/OneSignal(GameThrive.o)
    /Users/oussamtlili/Desktop/Wishibam-iOS/Pods/OneSignal/iOS_SDK/Framework/OneSignal.framework/OneSignal(OneSignalJailbreakDetection.o)
duplicate symbol _llvm.embedded.module in:
    /Users/oussamtlili/Desktop/Wishibam-iOS/Pods/OneSignal/iOS_SDK/Framework/OneSignal.framework/OneSignal(GameThrive.o)
    /Users/oussamtlili/Desktop/Wishibam-iOS/Pods/OneSignal/iOS_SDK/Framework/OneSignal.framework/OneSignal(OneSignalJailbreakDetection.o)
duplicate symbol _llvm.cmdline in:
    /Users/oussamtlili/Desktop/Wishibam-iOS/Pods/OneSignal/iOS_SDK/Framework/OneSignal.framework/OneSignal(GameThrive.o)
    /Users/oussamtlili/Desktop/Wishibam-iOS/Pods/OneSignal/iOS_SDK/Framework/OneSignal.framework/OneSignal(OneSignalHTTPClient.o)
duplicate symbol _llvm.embedded.module in:
    /Users/oussamtlili/Desktop/Wishibam-iOS/Pods/OneSignal/iOS_SDK/Framework/OneSignal.framework/OneSignal(GameThrive.o)
    /Users/oussamtlili/Desktop/Wishibam-iOS/Pods/OneSignal/iOS_SDK/Framework/OneSignal.framework/OneSignal(OneSignalHTTPClient.o)
duplicate symbol _llvm.cmdline in:
    /Users/oussamtlili/Desktop/Wishibam-iOS/Pods/OneSignal/iOS_SDK/Framework/OneSignal.framework/OneSignal(GameThrive.o)
    /Users/oussamtlili/Desktop/Wishibam-iOS/Pods/OneSignal/iOS_SDK/Framework/OneSignal.framework/OneSignal(OneSignalMobileProvision.o)
duplicate symbol _llvm.embedded.module in:
    /Users/oussamtlili/Desktop/Wishibam-iOS/Pods/OneSignal/iOS_SDK/Framework/OneSignal.framework/OneSignal(GameThrive.o)
    /Users/oussamtlili/Desktop/Wishibam-iOS/Pods/OneSignal/iOS_SDK/Framework/OneSignal.framework/OneSignal(OneSignalMobileProvision.o)
duplicate symbol _llvm.cmdline in:
    /Users/oussamtlili/Desktop/Wishibam-iOS/Pods/OneSignal/iOS_SDK/Framework/OneSignal.framework/OneSignal(GameThrive.o)
    /Users/oussamtlili/Desktop/Wishibam-iOS/Pods/OneSignal/iOS_SDK/Framework/OneSignal.framework/OneSignal(OneSignalReachability.o)
duplicate symbol _llvm.embedded.module in:
    /Users/oussamtlili/Desktop/Wishibam-iOS/Pods/OneSignal/iOS_SDK/Framework/OneSignal.framework/OneSignal(GameThrive.o)
    /Users/oussamtlili/Desktop/Wishibam-iOS/Pods/OneSignal/iOS_SDK/Framework/OneSignal.framework/OneSignal(OneSignalReachability.o)
duplicate symbol _llvm.cmdline in:
    /Users/oussamtlili/Desktop/Wishibam-iOS/Pods/OneSignal/iOS_SDK/Framework/OneSignal.framework/OneSignal(GameThrive.o)
    /Users/oussamtlili/Desktop/Wishibam-iOS/Pods/OneSignal/iOS_SDK/Framework/OneSignal.framework/OneSignal(OneSignal.o)
duplicate symbol _llvm.embedded.module in:
    /Users/oussamtlili/Desktop/Wishibam-iOS/Pods/OneSignal/iOS_SDK/Framework/OneSignal.framework/OneSignal(GameThrive.o)
    /Users/oussamtlili/Desktop/Wishibam-iOS/Pods/OneSignal/iOS_SDK/Framework/OneSignal.framework/OneSignal(OneSignal.o)
ld: 12 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jkasten2** [comment]
Make sure you are using Xcode 7.0 or newer when building for the simulator as OneSignal has bitcode enabled. Let us know exact version of Xcode you're using if this isn't the issue.

Thanks.

**Comment by tlilioussam** [comment]
I use Xcode 6.4

**Comment by jkasten2** [comment]
We recommend updating to Xcode 7.X if you can. If you need to stay on Xcode 6.4 you can use version 1.10.2 of our SDK.
https://github.com/one-signal/OneSignal-iOS-SDK/releases/tag/1.10.2

Thanks.
