### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by glancashire** [one-signal/OneSignal-iOS-SDK#16]
Dear Madams and Sirs

First thanks for a great service with a simple api.

However I get compilation errors, as I have an object called Category. This conflicts with the objc/runtime.h header file, which you import. 

Please comment out the following line in your header
#import <objc/runtime.h>
It works fine and my compilation errors disappear.

Kind Regards
Graham

**Comment by jkasten2** [comment]
Thanks for reporting the issue, I'll try it out in the next update.

**Comment by jkasten2** [comment]
Fixed in the 1.12.0 Release.
