### ISSUE TITLE
sendLocation: crash

### ISSUE THREAD

**Issue by mikemonaco** [one-signal/OneSignal-iOS-SDK#24]
Upgrade from 1.11.0 to 1.11.3, received the following crash on iOS 8.4

[sendLocationCrash.txt](https://github.com/one-signal/OneSignal-iOS-SDK/files/196990/sendLocationCrash.txt)

![screen shot 2016-03-31 at 12 43 29 am](https://cloud.githubusercontent.com/assets/2935352/14165707/d555ef46-f6d9-11e5-8edc-d94942562c90.png)

**Comment by vandyshev** [comment]
Same crash

**Comment by glancashire** [comment]
Same here too, on first launch

**Comment by jkasten2** [comment]
I believe this is from our 1.12.0 release. Looking into reproducing the issue now.

Do you have autoRegister disabled?
@vandyshev @glancashire Are you also seeing this on iOS 8.4 or a different version of iOS?

**Comment by vandyshev** [comment]
Yes. All is well when I set the 1.11.3.
1.12.1 crash. autoRegister default. ios 9.2.1 5s

**Comment by mikemonaco** [comment]
Auto-register is disabled here.

**Comment by jkasten2** [comment]
Thanks for the information everyone! Just fixed the issue in release 1.12.2.
