### ISSUE TITLE
One signal logging entire account config on init

### ISSUE THREAD

**Issue by nickfedoroff** [one-signal/OneSignal-iOS-SDK#25]
Since updating to 1.13.1, when I initialize OneSignal, I get the console output shown in the screenshot.

My log level is set like this:
`OneSignal.setLogLevel(.LL_NONE, visualLevel: .LL_NONE)`

![log](https://cloud.githubusercontent.com/assets/1442451/14444052/774895e0-0000-11e6-8998-c9324c9b293f.png)

**Comment by jkasten2** [comment]
Thanks for the report, just fixed in version 1.13.2.

**Comment by RayHughes** [comment]
Thanks much @jkasten2
