### ISSUE TITLE
Xcode 7 Dsymutil warnings (using the framework)

### ISSUE THREAD

**Issue by kalsky** [one-signal/OneSignal-iOS-SDK#3]
Hi

When adding the latest framework (from Sep 30) to a project, xcode 7 reports multiple warnings about the framework when it generates the DSYM file:

GenerateDSYMFile /Users/me/Library/Developer/Xcode/DerivedData/myapp-fgvmesatlqbktyaenkwgpeigbxek/Build/Products/Debug-iphonesimulator/myappLite.app.dSYM /Users/me/Library/Developer/Xcode/DerivedData/myapp-fgvmesatlqbktyaenkwgpeigbxek/Build/Products/Debug-iphonesimulator/myappLite.app/myappLite
    cd "/Users/me/Projects/myapp"
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil /Users/me/Library/Developer/Xcode/DerivedData/myapp-fgvmesatlqbktyaenkwgpeigbxek/Build/Products/Debug-iphonesimulator/myappLite.app/myappLite -o /Users/me/Library/Developer/Xcode/DerivedData/myapp-fgvmesatlqbktyaenkwgpeigbxek/Build/Products/Debug-iphonesimulator/myappLite.app.dSYM

while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(GameThrive.o):
warning: /var/folders/m3/4mw975vs0rx91dcstvctvn7r0000gn/C/org.llvm.clang.Kasten/ModuleCache/34JSGIDIJJSMG/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(GameThrive.o):
warning: /var/folders/m3/4mw975vs0rx91dcstvctvn7r0000gn/C/org.llvm.clang.Kasten/ModuleCache/34JSGIDIJJSMG/Foundation-3DFYNEBRQSXST.pcm: No object file for requested architecture
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(GameThrive.o):
warning: /var/folders/m3/4mw975vs0rx91dcstvctvn7r0000gn/C/org.llvm.clang.Kasten/ModuleCache/34JSGIDIJJSMG/ObjectiveC-1RQA2RIXJIE19.pcm: No such file or directory
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(GameThrive.o):
warning: /var/folders/m3/4mw975vs0rx91dcstvctvn7r0000gn/C/org.llvm.clang.Kasten/ModuleCache/34JSGIDIJJSMG/ObjectiveC-1RQA2RIXJIE19.pcm: No object file for requested architecture
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(GameThrive.o):
warning: Could not resolve external type c:objc(cs)NSString
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(GameThrive.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(GameThrive.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(GameThrive.o):
warning: Could not resolve external type c:objc(cs)NSDictionary
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(GameThrive.o):
warning: Could not resolve external type c:objc(cs)NSArray
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(GameThrive.o):
warning: Could not resolve external type c:objc(cs)NSNumber
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalTrackIAP.o):
warning: /var/folders/m3/4mw975vs0rx91dcstvctvn7r0000gn/C/org.llvm.clang.Kasten/ModuleCache/34JSGIDIJJSMG/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalTrackIAP.o):
warning: /var/folders/m3/4mw975vs0rx91dcstvctvn7r0000gn/C/org.llvm.clang.Kasten/ModuleCache/34JSGIDIJJSMG/Foundation-3DFYNEBRQSXST.pcm: No object file for requested architecture
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalTrackIAP.o):
warning: /var/folders/m3/4mw975vs0rx91dcstvctvn7r0000gn/C/org.llvm.clang.Kasten/ModuleCache/34JSGIDIJJSMG/ObjectiveC-1RQA2RIXJIE19.pcm: No such file or directory
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalTrackIAP.o):
warning: /var/folders/m3/4mw975vs0rx91dcstvctvn7r0000gn/C/org.llvm.clang.Kasten/ModuleCache/34JSGIDIJJSMG/ObjectiveC-1RQA2RIXJIE19.pcm: No object file for requested architecture
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalTrackIAP.o):
warning: Could not resolve external type c:objc(cs)NSMutableDictionary
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalTrackIAP.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalTrackIAP.o):
warning: Could not resolve external type c:objc(cs)NSArray
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalTrackIAP.o):
warning: Could not resolve external type c:objc(cs)NSString
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalTrackIAP.o):
warning: Could not resolve external type c:objc(cs)NSMutableArray
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalJailbreakDetection.o):
warning: /var/folders/m3/4mw975vs0rx91dcstvctvn7r0000gn/C/org.llvm.clang.Kasten/ModuleCache/34JSGIDIJJSMG/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalJailbreakDetection.o):
warning: /var/folders/m3/4mw975vs0rx91dcstvctvn7r0000gn/C/org.llvm.clang.Kasten/ModuleCache/34JSGIDIJJSMG/Foundation-3DFYNEBRQSXST.pcm: No object file for requested architecture
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalJailbreakDetection.o):
warning: /var/folders/m3/4mw975vs0rx91dcstvctvn7r0000gn/C/org.llvm.clang.Kasten/ModuleCache/34JSGIDIJJSMG/UIKit-1V5UHAPTOD24G.pcm: No such file or directory
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalJailbreakDetection.o):
warning: /var/folders/m3/4mw975vs0rx91dcstvctvn7r0000gn/C/org.llvm.clang.Kasten/ModuleCache/34JSGIDIJJSMG/UIKit-1V5UHAPTOD24G.pcm: No object file for requested architecture
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalJailbreakDetection.o):
warning: /var/folders/m3/4mw975vs0rx91dcstvctvn7r0000gn/C/org.llvm.clang.Kasten/ModuleCache/34JSGIDIJJSMG/ObjectiveC-1RQA2RIXJIE19.pcm: No such file or directory
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalJailbreakDetection.o):
warning: /var/folders/m3/4mw975vs0rx91dcstvctvn7r0000gn/C/org.llvm.clang.Kasten/ModuleCache/34JSGIDIJJSMG/ObjectiveC-1RQA2RIXJIE19.pcm: No object file for requested architecture
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalHTTPClient.o):
warning: /var/folders/m3/4mw975vs0rx91dcstvctvn7r0000gn/C/org.llvm.clang.Kasten/ModuleCache/34JSGIDIJJSMG/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalHTTPClient.o):
warning: /var/folders/m3/4mw975vs0rx91dcstvctvn7r0000gn/C/org.llvm.clang.Kasten/ModuleCache/34JSGIDIJJSMG/Foundation-3DFYNEBRQSXST.pcm: No object file for requested architecture
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalHTTPClient.o):
warning: /var/folders/m3/4mw975vs0rx91dcstvctvn7r0000gn/C/org.llvm.clang.Kasten/ModuleCache/34JSGIDIJJSMG/ObjectiveC-1RQA2RIXJIE19.pcm: No such file or directory
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalHTTPClient.o):
warning: /var/folders/m3/4mw975vs0rx91dcstvctvn7r0000gn/C/org.llvm.clang.Kasten/ModuleCache/34JSGIDIJJSMG/ObjectiveC-1RQA2RIXJIE19.pcm: No object file for requested architecture
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalHTTPClient.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalHTTPClient.o):
warning: Could not resolve external type c:objc(cs)NSURL
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalHTTPClient.o):
warning: Could not resolve external type c:objc(cs)NSMutableURLRequest
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalHTTPClient.o):
warning: Could not resolve external type c:objc(cs)NSString
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalMobileProvision.o):
warning: /var/folders/m3/4mw975vs0rx91dcstvctvn7r0000gn/C/org.llvm.clang.Kasten/ModuleCache/34JSGIDIJJSMG/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalMobileProvision.o):
warning: /var/folders/m3/4mw975vs0rx91dcstvctvn7r0000gn/C/org.llvm.clang.Kasten/ModuleCache/34JSGIDIJJSMG/Foundation-3DFYNEBRQSXST.pcm: No object file for requested architecture
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalMobileProvision.o):
warning: /var/folders/m3/4mw975vs0rx91dcstvctvn7r0000gn/C/org.llvm.clang.Kasten/ModuleCache/34JSGIDIJJSMG/Darwin-38I6DLZ5IH61J.pcm: No such file or directory
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalMobileProvision.o):
warning: /var/folders/m3/4mw975vs0rx91dcstvctvn7r0000gn/C/org.llvm.clang.Kasten/ModuleCache/34JSGIDIJJSMG/Darwin-38I6DLZ5IH61J.pcm: No object file for requested architecture
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalMobileProvision.o):
warning: /var/folders/m3/4mw975vs0rx91dcstvctvn7r0000gn/C/org.llvm.clang.Kasten/ModuleCache/34JSGIDIJJSMG/ObjectiveC-1RQA2RIXJIE19.pcm: No such file or directory
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalMobileProvision.o):
warning: /var/folders/m3/4mw975vs0rx91dcstvctvn7r0000gn/C/org.llvm.clang.Kasten/ModuleCache/34JSGIDIJJSMG/ObjectiveC-1RQA2RIXJIE19.pcm: No object file for requested architecture
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalMobileProvision.o):
warning: Could not resolve external type c:objc(cs)NSDictionary
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalMobileProvision.o):
warning: Could not resolve external type c:objc(cs)NSString
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalMobileProvision.o):
warning: Could not resolve external type c:objc(cs)NSScanner
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalMobileProvision.o):
warning: Could not resolve external type c:objc(cs)NSData
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalMobileProvision.o):
warning: Could not resolve external type c:objc(cs)NSError
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalReachability.o):
warning: /var/folders/m3/4mw975vs0rx91dcstvctvn7r0000gn/C/org.llvm.clang.Kasten/ModuleCache/34JSGIDIJJSMG/Darwin-38I6DLZ5IH61J.pcm: No such file or directory
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalReachability.o):
warning: /var/folders/m3/4mw975vs0rx91dcstvctvn7r0000gn/C/org.llvm.clang.Kasten/ModuleCache/34JSGIDIJJSMG/Darwin-38I6DLZ5IH61J.pcm: No object file for requested architecture
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalReachability.o):
warning: /var/folders/m3/4mw975vs0rx91dcstvctvn7r0000gn/C/org.llvm.clang.Kasten/ModuleCache/34JSGIDIJJSMG/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalReachability.o):
warning: /var/folders/m3/4mw975vs0rx91dcstvctvn7r0000gn/C/org.llvm.clang.Kasten/ModuleCache/34JSGIDIJJSMG/Foundation-3DFYNEBRQSXST.pcm: No object file for requested architecture
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalReachability.o):
warning: /var/folders/m3/4mw975vs0rx91dcstvctvn7r0000gn/C/org.llvm.clang.Kasten/ModuleCache/34JSGIDIJJSMG/CoreFoundation-J9ZOXGK4ZTRR.pcm: No such file or directory
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalReachability.o):
warning: /var/folders/m3/4mw975vs0rx91dcstvctvn7r0000gn/C/org.llvm.clang.Kasten/ModuleCache/34JSGIDIJJSMG/CoreFoundation-J9ZOXGK4ZTRR.pcm: No object file for requested architecture
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalReachability.o):
warning: /var/folders/m3/4mw975vs0rx91dcstvctvn7r0000gn/C/org.llvm.clang.Kasten/ModuleCache/34JSGIDIJJSMG/SystemConfiguration-354UAJE49HRJF.pcm: No such file or directory
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalReachability.o):
warning: /var/folders/m3/4mw975vs0rx91dcstvctvn7r0000gn/C/org.llvm.clang.Kasten/ModuleCache/34JSGIDIJJSMG/SystemConfiguration-354UAJE49HRJF.pcm: No object file for requested architecture
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalReachability.o):
warning: /var/folders/m3/4mw975vs0rx91dcstvctvn7r0000gn/C/org.llvm.clang.Kasten/ModuleCache/34JSGIDIJJSMG/ObjectiveC-1RQA2RIXJIE19.pcm: No such file or directory
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalReachability.o):
warning: /var/folders/m3/4mw975vs0rx91dcstvctvn7r0000gn/C/org.llvm.clang.Kasten/ModuleCache/34JSGIDIJJSMG/ObjectiveC-1RQA2RIXJIE19.pcm: No object file for requested architecture
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalReachability.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalReachability.o):
warning: Could not resolve external type c:@S@sockaddr_in
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalReachability.o):
warning: Could not resolve external type c:@S@sockaddr_in
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalReachability.o):
warning: Could not resolve external type c:@E@SCNetworkReachabilityFlags
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignalReachability.o):
warning: Could not resolve external type c:objc(cs)NSString
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignal.o):
warning: /var/folders/m3/4mw975vs0rx91dcstvctvn7r0000gn/C/org.llvm.clang.Kasten/ModuleCache/34JSGIDIJJSMG/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignal.o):
warning: /var/folders/m3/4mw975vs0rx91dcstvctvn7r0000gn/C/org.llvm.clang.Kasten/ModuleCache/34JSGIDIJJSMG/Foundation-3DFYNEBRQSXST.pcm: No object file for requested architecture
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignal.o):
warning: /var/folders/m3/4mw975vs0rx91dcstvctvn7r0000gn/C/org.llvm.clang.Kasten/ModuleCache/34JSGIDIJJSMG/ObjectiveC-1RQA2RIXJIE19.pcm: No such file or directory
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignal.o):
warning: /var/folders/m3/4mw975vs0rx91dcstvctvn7r0000gn/C/org.llvm.clang.Kasten/ModuleCache/34JSGIDIJJSMG/ObjectiveC-1RQA2RIXJIE19.pcm: No object file for requested architecture
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignal.o):
warning: /var/folders/m3/4mw975vs0rx91dcstvctvn7r0000gn/C/org.llvm.clang.Kasten/ModuleCache/34JSGIDIJJSMG/SystemConfiguration-354UAJE49HRJF.pcm: No such file or directory
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignal.o):
warning: /var/folders/m3/4mw975vs0rx91dcstvctvn7r0000gn/C/org.llvm.clang.Kasten/ModuleCache/34JSGIDIJJSMG/SystemConfiguration-354UAJE49HRJF.pcm: No object file for requested architecture
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignal.o):
warning: /var/folders/m3/4mw975vs0rx91dcstvctvn7r0000gn/C/org.llvm.clang.Kasten/ModuleCache/34JSGIDIJJSMG/Darwin-38I6DLZ5IH61J.pcm: No such file or directory
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignal.o):
warning: /var/folders/m3/4mw975vs0rx91dcstvctvn7r0000gn/C/org.llvm.clang.Kasten/ModuleCache/34JSGIDIJJSMG/Darwin-38I6DLZ5IH61J.pcm: No object file for requested architecture
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignal.o):
warning: /var/folders/m3/4mw975vs0rx91dcstvctvn7r0000gn/C/org.llvm.clang.Kasten/ModuleCache/34JSGIDIJJSMG/UIKit-1V5UHAPTOD24G.pcm: No such file or directory
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignal.o):
warning: /var/folders/m3/4mw975vs0rx91dcstvctvn7r0000gn/C/org.llvm.clang.Kasten/ModuleCache/34JSGIDIJJSMG/UIKit-1V5UHAPTOD24G.pcm: No object file for requested architecture
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignal.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignal.o):
warning: Could not resolve external type c:objc(cs)NSString
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignal.o):
warning: Could not resolve external type c:objc(cs)NSDictionary
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignal.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignal.o):
warning: Could not resolve external type c:objc(cs)NSURL
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignal.o):
warning: Could not resolve external type c:objc(cs)NSMutableDictionary
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignal.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignal.o):
warning: Could not resolve external type c:objc(cs)NSNumber
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignal.o):
warning: Could not resolve external type c:objc(cs)NSMutableArray
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignal.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignal.o):
warning: Could not resolve external type c:@S@utsname
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignal.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignal.o):
warning: Could not resolve external type c:objc(cs)NSArray
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignal.o):
warning: Could not resolve external type c:objc(cs)NSUserDefaults
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignal.o):
warning: Could not resolve external type c:objc(cs)UIAlertView
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignal.o):
warning: Could not resolve external type c:objc(cs)NSMutableURLRequest
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignal.o):
warning: Could not resolve external type c:objc(cs)NSData
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignal.o):
warning: Could not resolve external type c:objc(cs)NSFileManager
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignal.o):
warning: Could not resolve external type c:objc(cs)NSError
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignal.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignal.o):
warning: Could not resolve external type c:objc(cs)NSURLRequest
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignal.o):
warning: Could not resolve external type c:objc(cs)NSURLResponse
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignal.o):
warning: Could not resolve external type c:objc(cs)NSHTTPURLResponse
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignal.o):
warning: Could not resolve external type c:objc(cs)UIApplication
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignal.o):
warning: Could not resolve external type c:objc(cs)UILocalNotification
while processing /Users/me/Projects/myapp/OneSignal.framework/OneSignal(OneSignal.o):
warning: Could not resolve external type c:objc(cs)UIUserNotificationSettings

**Comment by kalsky** [comment]
I recompiled the OneSignal project and then used the compiled version and the warnings were removed.

**Comment by jkasten2** [comment]
@kalsky I haven't been able to reproduce this issue. However I just updated to Xcode 7.0.1 and recompiled the framework as Apple noted that there has been fixes for bitcode. Can you try the framework file from commit eeab97b75dc9fbed9c31abc6d43959ce8168d634 and build with Xocde 7.0.1 on your system?

Thanks.

**Comment by jefflovejapan** [comment]
Issue isn't resolved for me. Using as a development pod, verified that it's commit eeab97b. Using Xcode 7.0.1 (7A1001).

**Comment by jkasten2** [comment]
@jefflovejapan @kalsky I just downloaded the compiled a new project without warnings with commit eeab97b on a different mac with a fresh install of Xcode 7.0.1. Can you provide an example project reproducing the warnings?

Can you try the following settings in your project with the framework folder included in this repository to see if it fixes the warning for you?
https://forums.developer.apple.com/thread/17921

Thanks.

**Comment by valeriomazzeo** [comment]
I am having the same problem, fresh project just installing OneSignal though cocoapods on Xcode 7.0.1

**Comment by jkasten2** [comment]
Just released version 1.10.4 which has dSYM disabled. Let me know if this fixes the warnings for everyone.

Thanks.

**Comment by jefflovejapan** [comment]
@jkasten2 Unfortunately I'm still getting the warnings with 1.10.4 on my existing project. I'll try again with a fresh project tonight.

**Comment by jkasten2** [comment]
I was able to reproduce the warning issue after clearing the cache directory on the macs I was testing on. I changed the build setting in commit d04a36b964cf488f85dc9c4b61ff24eb7c4e4b0a and have released version 1.10.5 to cocoapods.

If you're still seeing these warnings after updating feel free to reopen this issue.

Thanks.
