### ISSUE TITLE
How to reset iOS Push Notifications Badge number?

### ISSUE THREAD

**Issue by ADevelopStudio** [one-signal/OneSignal-iOS-SDK#31]
I'me sending push with everytime with "increase by 1".
After opening the App I set badge = 0 to remove it from app icon, however next notification increases my badge by 1 again (from 9 to 10 for example) even if I cleared the badge before. 
So,
How to reset iOS Push Notifications Badge number?

**Comment by jkasten2** [comment]
@ADevelopStudio The badge number should automatically be cleared from the device by the SDK. Then it will make a REST API call to reset it on the OneSignal server so it should start over from 0.

**Comment by ADevelopStudio** [comment]
I meant, do i need to put special any api request in applicationDidBecomeActive ?

**Comment by jkasten2** [comment]
The [SDK automatically hooks](https://github.com/one-signal/OneSignal-iOS-SDK/blob/master/iOS_SDK/OneSignal/OneSignal.m#L1440) into `applicationDidBecomeActive` to clear the badge count when resuming the app. If you remove you own clearing code does the badge count get cleared from the device when you resume your app?

**Comment by ADevelopStudio** [comment]
To be honest, I couldn't reproduce that on my devices. When I open the app my badge counter resets. however, my client said that on his device new push just increases the badge number even if he opened app before and badge was cleaned by the app as:
`        UIApplication.sharedApplication().applicationIconBadgeNumber = 0
`
I installed OneSignal to my app via CocoaPods, hope it doesn't matter

**Comment by jkasten2** [comment]
Just confirm, the badge count is resting without adding the following line to your code to your app?
`UIApplication.sharedApplication().applicationIconBadgeNumber = 0;`

And only your client is seeing the badge increase issue?

Using CocoaPods would not effect this.

Can you have them restart their iOS device? I have seen iOS's badge number get stuck in the past and restarting the device fixes the issue.

**Comment by ADevelopStudio** [comment]
you're right, when I remove my clearing code, the badge clears by OneSignal, I suppose this solves my issue.  Thanks!

**Comment by Ankush-Redapple** [comment]
Please follow https://documentation.onesignal.com/docs/ios-sdk-app-groups-setup in detail.

> The name of your app group should be group.{your_bundle_id}.onesignal. So for example, if your application's bundle identifier is com.test.app, your app group name should be group.com.test.app.onesignal.
> 
> [Assign the group to both target](https://files.readme.io/9e17c8c-OneSignal_Xcode_app_groups_capabilites.png).
> 
> 1. Open your Info.plist file and add a new OneSignal_app_groups_key as a String type.
> 2. Enter the group name you checked in the last step as it's value.
> 3. Make sure to do the same for the Info.plist under the OneSignalNotificationServiceExtension folder.
