### ISSUE TITLE
Background data for iOS swift

### ISSUE THREAD

**Issue by mychaelgo** [one-signal/OneSignal-iOS-SDK#32]
is there similar function same as NotificationExtenderService in android?

**Comment by jkasten2** [comment]
There is not since displaying of notifications are handled by iOS itself.

**Comment by jkasten2** [comment]
However if you just need to get background data you can enable content_available and the following function will be called in your AppDelegate.
[application(_:didReceiveRemoteNotification:fetchCompletionHandler:)](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIApplicationDelegate_Protocol/#//apple_ref/occ/intfm/UIApplicationDelegate/application:didReceiveRemoteNotification:fetchCompletionHandler:)

**Comment by mychaelgo** [comment]
okay i will try. thanks :)
