### ISSUE TITLE
Get push token as NSData type

### ISSUE THREAD

**Issue by alvivi** [one-signal/OneSignal-iOS-SDK#4]
Right now you can get current user token using `IdsAvailable`, but that returns the token as String. Apple returns this token as an NSData parameter and other libraries expect a NSData as push token type.

**Comment by jkasten2** [comment]
Would using the [application:didRegisterForRemoteNotificationsWithDeviceToken:](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIApplicationDelegate_Protocol/index.html?hl=ar#//apple_ref/occ/intfm/UIApplicationDelegate/application:didRegisterForRemoteNotificationsWithDeviceToken:) native selector in your app work for you? If not let us know.

Thanks.

**Comment by jkasten2** [comment]
Feel free to reopen this issue if the above selector does not work for your use case.

Thanks.
