### ISSUE TITLE
Linker error with cocoapods

### ISSUE THREAD

**Issue by cassidyclawson** [one-signal/OneSignal-iOS-SDK#5]
I am getting the following error when trying to build for 9.1 using Cocoapods.

```Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_OneSignal", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)```

I've gone through the cocoapods debugging steps here: http://stackoverflow.com/questions/19213782/undefined-symbols-for-architecture-arm64

Any insight?

**Comment by jkasten2** [comment]
Hello,

Sorry for the late response, are you still seeing this issue? If so can you let us know the version of Cocoapods you are using? Can you reproduce the issue with a new project and share it with us?

Thanks.

**Comment by lukasz-kusnierz** [comment]
This is a CocoaPods issue. I was able to fix it by appending **$(inherited)** to **Other Linker Flags** in my *target*.

**Comment by jkasten2** [comment]
@lukasz-kusnierz thanks for the information!

**Comment by adamrainsby** [comment]
Thanks @lukasz-kusnierz

**Comment by faustoct** [comment]
fixed running `pod install`
