### ISSUE TITLE
impossible to run on simulator

### ISSUE THREAD

**Issue by Hope4hope** [one-signal/OneSignal-iOS-SDK#8]
Xcode Version 7.2 (7C68), OneSignal-iOS-SDK-1.10.6, testing in simulator always give this error: OneSignal-iOS-SDK-master/OneSignalExample/OneSignal-iOS-SDK-1.10.6/Framework/OneSignal.framework/OneSignal(OneSignal.o) 

ld: 38 duplicate symbols for architecture x86_64 
clang: error: linker command failed with exit code 1 (use -v to see invocation)

dead end ....

**Comment by Hope4hope** [comment]
Fixed,it was my mistake,

**Comment by jkasten2** [comment]
Could you let us know how you were able to fix the issue? This will help anyone else who may find this issue.

Thanks.

**Comment by tlilioussam** [comment]
I have the same issue but i don't find solution

**Comment by podvipodvert** [comment]
@Hope4hope how do you fix that?
