### ISSUE TITLE
swift with cocoapods and use_frameworks! does not compile

### ISSUE THREAD

**Issue by mihai-moldovan** [one-signal/OneSignal-iOS-SDK#9]
I'm using cocoapods version 1.0.0.beta.2, xcode 7.2.1 on Mac OS El Capitan. 
I managed to reproduce it with a vanilla projects. So here are the steps:

- Create a new Swift ios project
- In terminal run 'pod init'
- in the newly created Podfile uncomment _use_frameworks!_ and add _pod 'OneSignal'_ 
- run pod install
- open the .xcworkspace file
- In AppDelegate.swift try to use OneSignal  - it cannot be found; try to import OneSignal - module cannot be found.
Although the framework is present in the Pods folder. There are other frameworks distributed like OneSignal  and they do work with use_frameworks (for example: Fabric)

All the steps above have been applied to the project in the attached archive

Maybe I'm doing something wrong, so any help is greatly appreciated.
[example.zip](https://github.com/one-signal/OneSignal-iOS-SDK/files/120181/example.zip)

**Comment by jkasten2** [comment]
Hello,

Thanks for the detailed steps on reproducing the issue, we will try it out and get back to you.

In the meantime you can follow our instructions [3B. Swift](https://documentation.onesignal.com/docs/installing-the-onesignal-ios-sdk#3b-swift-click-to-expand) to add the required bridging header. Let us know if you still see an issue after this.

Thanks.

**Comment by mihai-moldovan** [comment]
Thanks, I've managed to integrate it with the bridging header. I thought one cannot use both bridging header and use_frameworks! in the same project.

Silly me
